import fs from 'node:fs/promises';
import path from 'node:path';
import { config } from './config.js';
import { withState } from './store.js';
import type { Lead } from './types.js';

function safeFileName(value: string): string {
  return String(value || 'lead').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '').slice(0, 80) || 'lead';
}

function renderLeadHomepage(lead: Lead): string {
  const title = lead.company || 'Local Business';
  const phone = lead.phone || 'Call now';
  const summary = lead.prospectSummary || lead.findings || 'Premium local business homepage concept.';
  const cityState = [lead.prospectCity, lead.prospectState].filter(Boolean).join(', ');
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${title}</title>
  <style>
    body{margin:0;font-family:Inter,Arial,sans-serif;background:#f8fafc;color:#0f172a}
    .hero{padding:80px 24px;background:linear-gradient(135deg,#0f172a,#7c3aed);color:#fff}
    .wrap{max-width:1100px;margin:0 auto}.cta{display:inline-block;padding:14px 22px;border-radius:999px;background:#22c55e;color:#052e16;text-decoration:none;font-weight:700}
    .section{padding:56px 24px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:22px}.card{background:#fff;border-radius:18px;padding:24px;box-shadow:0 12px 28px rgba(15,23,42,.08)}
    h1{font-size:48px;line-height:1.02;margin:0 0 12px} h2{margin:0 0 12px;font-size:26px}
  </style>
</head>
<body>
  <section class="hero"><div class="wrap"><p>${cityState || 'Local market'} • ${lead.prospectIcp || 'Premium service brand'}</p><h1>${title}</h1><p style="max-width:760px;font-size:18px;line-height:1.6">${summary}</p><p><a class="cta" href="tel:${phone}">Call ${phone}</a></p></div></section>
  <section class="section"><div class="wrap grid"><div class="card"><h2>Why Clients Choose Us</h2><p>Trust-first positioning, premium presentation, and a strong consultative CTA built for conversion.</p></div><div class="card"><h2>Featured Services</h2><p>Structured service highlights aligned with the business category and local buyer intent.</p></div><div class="card"><h2>Service Area</h2><p>${cityState || 'Primary local market'} and nearby communities.</p></div></div></section>
  <section class="section"><div class="wrap card"><h2>Frequently Asked Questions</h2><p>Answer common objections, reinforce credibility, and move visitors toward booking.</p><h2>Contact</h2><p>Phone: ${phone}</p><p>Website demo generated by TRD Voice Ops.</p></div></section>
</body>
</html>`;
}

export async function generateReadyProspectSites(limit = 10): Promise<{ generated: number; leads: string[] }> {
  await fs.mkdir(config.generatedSitesDir, { recursive: true });
  const generated: string[] = [];
  await withState(async (state) => {
    const ready = Object.values(state.leads)
      .filter((lead) => lead.sourceFile === 'prospector-dashboard' && lead.generationStatus === 'ready')
      .slice(0, limit);

    for (const lead of ready) {
      const fileName = `${safeFileName(lead.company || lead.id)}-${safeFileName(lead.id)}.html`;
      const fullPath = path.resolve(config.generatedSitesDir, fileName);
      await fs.writeFile(fullPath, renderLeadHomepage(lead), 'utf8');
      lead.generatedSitePath = fullPath;
      lead.generationStatus = 'generated';
      lead.updatedAt = new Date().toISOString();
      generated.push(lead.id);
    }
  });
  return { generated: generated.length, leads: generated };
}
